version: '2'
services:

  web:
    restart: always
    build:  # configuration options applied at build time
      context: ./web
      dockerfile: ./Dockerfile
    volumes:
      - ./web:/web
    expose:
      - "8000"
    #command: tail -f /dev/null  # override Dockerfile cmd, keep container up so not an automatic exit
    command: sh /web/scripts/post-run-uwsgi.sh  # run uwsgi script

  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    links:
      - web
    volumes:
      - ./web/:/web
    ports:
      - "80:80"